In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from preprocess import *

In [2]:
df = pd.read_csv("[24-2 DS_Project2] Data.csv")

In [3]:
preprocessor = PreProc()

In [4]:
num_columns = [
    'Current Age', 
    'Retirement Age', 
    'Per Capita Income - Zipcode', 
    'Yearly Income',
    'Total Debt',
    'Credit Score',
    'Credit Limit',
    'Amount',
]
cat_columns = [
    'Gender',
    'Zipcode',
    'Card Brand',
    'Card Type',
    'Expires',
    'Has Chip',
    'Acct Open Date',
    'Year PIN last Changed',
    'Merchandise Code',
    'Whether Security Chip is Used',
    'Error Message',
    'Year',
    'Month',
    'Day',
]
discarded = [
    'User',
    'Birth Year',
    'Birth Month',
    'Card',
    'Card Number',
]

In [5]:
t = Cleanse(df, cat_columns)

In [6]:
(cat_df, num_df) = preprocessor.preprocess(df, cat_columns, num_columns, discarded)

target mapping...
discard features...
num_features IQR...
num_features Scaling...
cat_features Cleansing...
complete preprocessing...

In [7]:
y = Target(df)

0          False
1          False
2          False
3          False
4          False
           ...
1644763    False
1644764    False
1644765    False
1644766    False
1644767    False
Name: Is Fraud?, Length: 1644768, dtype: bool

In [8]:
(train_cat_X, train_num_X, train_y), (valid_cat_X, valid_num_X, valid_y) = preprocessor.TVsplit(Cleanse(df, cat_columns), Scale(df, num_columns), Target(df))

,Current Age,Retirement Age,Per Capita Income - Zipcode,Yearly Income,Total Debt,Credit Score,Credit Limit,Amount
0,0.054186,-0.248502,1.242624,2.866050,2.313088,0.693214,1.328897,2.533367
1,0.054186,-0.248502,1.242624,2.866050,2.313088,0.693214,1.328897,-0.735081
2,0.054186,-0.248502,1.242624,2.866050,2.313088,0.693214,1.328897,1.806518
3,0.054186,-0.248502,1.242624,2.866050,2.313088,0.693214,1.328897,0.219800
4,0.054186,-0.248502,1.242624,2.866050,2.313088,0.693214,1.328897,-0.853847
...,...,...,...,...,...,...,...,...
1179824,-0.321742,0.154816,-0.961841,-1.049092,0.157910,0.553194,-0.903665,-0.825343
1179825,-0.321742,0.154816,-0.961841,-1.049092,0.157910,0.553194,-0.903665,-0.891852
1179826,-0.321742,0.154816,-0.961841,-1.049092,0.157910,0.553194,-0.903665,0.979904
1179827,-0.321742,0.154816,-0.961841,-1.049092,0.157910,0.553194,-0.903665,0.063029
1179828,-0.321742,0.154816,-0.961841,-1.049092,0.157910,0.553194,-0.903665,0.381322

,Gender,Zipcode,Card Brand,Card Type,Expires,Has Chip,Acct Open Date,Year PIN last Changed,Merchandise Code,Whether Security Chip is Used,Error Message,Year,Month,Day
0,0,1142,2,1,57,1,198,6,74,0,17,0,0,11
1,0,1142,2,1,57,1,198,6,56,0,17,0,0,26
2,0,1142,2,1,57,1,198,6,72,1,17,0,0,26
3,0,1142,2,1,57,1,198,6,56,0,17,0,0,27
4,0,1142,2,1,57,1,198,6,59,0,17,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644763,0,1349,2,0,55,1,118,15,90,0,17,0,3,23
1644764,0,1349,2,0,55,1,118,15,35,1,17,0,3,23
1644765,0,1349,2,0,55,1,118,15,55,1,17,0,3,24
1644766,0,1349,2,0,55,1,118,15,90,0,17,0,3,24
1644767,0,1349,2,0,55,1,118,15,35,0,17,0,3,24

0          False
1          False
2          False
3          False
4          False
           ...
1644763    False
1644764    False
1644765    False
1644766    False
1644767    False
Name: Is Fraud?, Length: 1644768, dtype: bool